baseURL: "https://blog.huzaifamustafa.com/"
title: Huzaifa Mustafa
paginate: 5
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
# googleAnalytics: UA-123-45

minify:
  disableXML: true
  # minifyOutput: true

languages:
  en:
    languageName: "English"
    weight: 1
    menu:
      main:
        - name: General
          url: /posts/
          weight: 5
        - name: Shopware
          url: shopware
          weight: 10
        - name: Technology
          url: technology
          weight: 15
        - name: About
          url: /posts/about/
          weight: 20

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  description: "Blog to talk about technology, Shopware, and whatever else I feel like!"
  author: Huzaifa
  defaultTheme: auto
  # disableThemeToggle: true
  ShowShareButtons: true
  ShowReadingTime: true
  # disableSpecial1stPost: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowToc: false
  # comments: false
  images: [ "draft-cover.png" ]

  profileMode:
    enabled: false
    title: Huzaifa Mustafa
    imageUrl: "/me.png"
    imageTitle: my image
    # imageWidth: 120
    # imageHeight: 120
    buttons:
      - name: Archives
        url: archives
      - name: Tags
        url: tags

  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: >
      ### My name is Huzaifa Mustafa.

      ---

      I am a full-stack developer with more than seven years of professional development experience.
      I am here to blog about tech, and whatever else I feel like!

  socialIcons:
    - name: github
      url: "https://github.com/zaifastafa/huzaifa-blog"
    - name: twitter
      url: "https://twitter.com/_huzaifamustafa"
    - name: me
      url: "https://huzaifamustafa.com"
  #    - name: RsS
  #      url: "index.xml"

  #  editPost:
  #    URL: "https://github.com/adityatelange/hugo-PaperMod/tree/exampleSite/content"
  #    Text: "Suggest Changes" # edit text
  #    appendFilePath: true # to append file path to Edit link

  label:
    text: "Huzaifa's Blog"
    icon: /me.png
    iconHeight: 35

  # analytics:
  #     google:
  #         SiteVerificationTag: "XYZabc"

  # assets:
  #     favicon: "<link / abs url>"
  #     favicon16x16: "<link / abs url>"
  #     favicon32x32: "<link / abs url>"
  #     apple_touch_icon: "<link / abs url>"
  #     safari_pinned_tab: "<link / abs url>"

  # cover:
  #     hidden: true # hide everywhere but not in structured data
  #     hiddenInList: true # hide on list pages and home
  #     hiddenInSingle: true # hide on single page

#   fuseOpts:
#       isCaseSensitive: false
#       shouldSort: true
#       location: 0
#       distance: 1000
#       threshold: 0.4
#       minMatchCharLength: 0
#       keys: ["title", "permalink", "summary", "content"]

#taxonomies:
#  category: categories
#  tag: tags
#  series: series

markup:
  goldmark:
    renderer:
      unsafe: true
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         # noClasses: false
#         style: monokai

privacy:
  vimeo:
    disabled: false
    simple: true

  twitter:
    disabled: false
    enableDNT: true
    simple: true

  instagram:
    disabled: false
    simple: true

  youtube:
    disabled: false
    privacyEnhanced: true

services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true
